# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  test:
  
    docker:
      - image: cimg/android:2023.06
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Download Dependencies"
          command: |
            chmod +x gradlew
            ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
   
      - run:
          name: Run tests
          command: ./gradlew test
      - store_test_results:
          path: /tmp/results


  build:
  
    docker:
      - image: cimg/android:2023.06
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Download Dependencies"
          command: |
            chmod +x gradlew
            ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
   
      - run:
          name: Build Library
          command: ./gradlew assemble
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - /tmp/workspaces
      - store_artifacts:
          path: /tmp/artifacts

  deploy:
  
    docker:
      - image: cimg/android:2023.06
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Download Dependencies
          command: |
            chmod +x gradlew
            ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Publish library
          command: ./gradlew publish

      

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - test
      - build
      - deploy
