# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  test:
  
    docker:
      - image: cimg/android:2023.06
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Download Dependencies"
          command: |
            chmod +x gradlew
            ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
   
      - run:
          name: Run tests
          command: ./gradlew test
      - store_test_results:
          path: build/test-results/testDebugUnitTest/


  build:
  
    docker:
      - image: cimg/android:2023.06
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Download Dependencies"
          command: |
            chmod +x gradlew
            ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
   
      - run:
          name: Build Library
          command: ./gradlew assemble

      - store_artifacts:
          path: build/outputs/aar


  deploy:

    docker:
      - image: cimg/android:2023.06
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Download Dependencies
          command: |
            chmod +x gradlew
            ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Publish library
          command: ./gradlew publish

  trigger-children-pipelines:
    docker:
      - image: cimg/base:2023.06
    resource_class: small
    steps:
      - run:
          name: Trigger children pipelines
          command: |
            echo $CIRCLECI_API_TOKEN
            curl --request POST \
              --url https://circleci.com/api/v2/project/github/nuilewis/customtestapp/pipeline \
              --header "Circle-Token: CCIPAT_6YvAWvjrYpvgdStvYpnMZb_7bfe7c3b54405ccc9f6be7ac460fbe30612c1ce5" \
              --header "content-type: application/json" \
              --data '{"branch":"main"}' \
            
#you can pass info such as the latest version of the deploy library
#so it would be used by the downstream pipelines

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-build-publish-workflow:
    jobs:
      # - test
      # - build:
      #     requires:
      #       - test
      # - deploy:
      #     requires:
      #       - build
      # - trigger-children-pipelines:
      #     requires:
      #       - deploy
      - trigger-children-pipelines
